### PR TITLE
This fixes classicdb/database#691

### PR DESCRIPTION
**Pull request by y1x2**
Triggered via EVENT_T_SPELLHIT 
-> SpellId = 10768 (Skinning (Artisan)) since a skinning skill of 315 is required at least.

### CODE REVIEW

**Comment by X-Savior** [comment]
this looks like a hack... Because there is multiple levels of skinning.

There has never been an approach like this. I suspect DB Scripts or something might be required.

Cala and Tobi... can you elaborate on this please.

**Comment by xfurry** [comment]
@y1x2 this event won't work when the creature is dead.
One possible fix would be to enable this in the core while the creature is dead. However we might need more info on this.

Also I agree with @X-Savior, there are many skinning spells, so we might not know which one to use.

Another possible solution would be to add event for EVENT_T_CORPSE_REMOVED or use the OnCreatureDespawn function in SD2, but we won't be able to tell whether this is happening by default or by skinning.

**Comment by y1x2** [comment]
Are you sure it isn't working? I did some debugging before and the core seems to handle it quite well without any modification.
Some comment to the single spell issue:
As long as you need a skinning skill of atleast 315 Skinning (Artisan) is required to trigger the event. So i'm pretty sure about this being correct. But i'll elaborate on this when i'm back home...

**Comment by cala** [comment]
There are many ways to have it working, but I'm not sure which one is better:
- using EVENT_T_SPELLHIT with SpellId = 10768 for Classic (and spells of higher ranks for TBC/WotLK)
- using some scripted method like what is roughly suggested here: https://github.com/scriptdev2/scriptdev2/issues/128#issuecomment-69148648

There is probably other ways, I did not truly look at this yet to be honest. This issue being a very specific case, moreover in a dungeon, I would be inclined to go one of the SD2 way.

**Comment by xfurry** [comment]
> using some scripted method like what is roughly suggested here: scriptdev2/scriptdev2#128 (comment)

This will not work. You can't know if they corpse was removed from skinning or by default.
It has to be linked to the skinning spells. I guess that adding a few spells in spellhit won't hurt, but we need to know for sure which are these spells.

**Comment by Rushor** [comment]
spell=10768
spell=8617
spell=8618
spell=32678
spell=50305

cata/mop/wod missing

and yeah we could say, that the corpsedespawn of the npc is by default set to : 7 days, so the npc never despawn manually, only way to let him despawn then, will be do do skinning on him, and only then the corpseremove will be called.

but i don't know if this creature never despawned. blizz sometimes scripts strange stuff

**Comment by xfurry** [comment]
Fixed in SD2 [3109] https://github.com/scriptdev2/scriptdev2/commit/f828f733b84e9bf39e59ce9d6fd3a9265a5316a9

**Pull request closed without merging**
